name: pinepods_mobile
description: Pinepods Podcast Server

version: 0.7.8

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: 3.27.0

dependencies:
  accessibility_tools: ^2.3.0
  app_links: ^6.3.0
  auto_size_text: ^3.0.0
  audio_service: ^0.18.17
  audio_session: ^0.1.23
  collection: ^1.18.0
  connectivity_plus: ^6.0.11
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.2.0
  extended_image: ^9.1.0
  file_picker: ^8.1.7
  flutter_dialogs: ^3.0.0
  flutter_downloader: ^1.11.8
  flutter_html: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.14.2
  flutter_spinkit: ^5.0.0
  html: ^0.15.0
  intl: ^0.19.0
  intl_translation: ^0.20.0
  just_audio: ^0.9.46
  logging: ^1.0.2
  meta: ^1.12.0
  mp3_info: ^0.2.0
  path: ^1.8.3
  path_provider: ^2.1.4
  path_provider_platform_interface: ^2.0.4
  percent_indicator: 4.2.4
  permission_handler: ^11.1.0
  podcast_search: ^0.7.4
  provider: ^6.0.3
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.7
  sembast: ^3.8.3
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.1
  xml: 6.5.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^5.2.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Override layout grid to fix dependency issue with flutter_html_table
  flutter_layout_grid: ^2.0.5

flutter_icons:
  image_path_android: "../images/favicon.png"
  image_path_ios: "../images/icon-512.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - ../images/favicon.png
    - ../images/icon-192.png
    - ../images/icon-512.png
    - ../images/1.jpg
    - ../images/2.jpg
    - ../images/3.jpg
    - ../images/4.jpg
    - ../images/5.jpg
    - ../images/6.jpg
    - ../images/7.jpg
    - ../images/8.jpg
    - ../images/9.jpg

    # Certificate authorities
    - assets/ca/lets-encrypt-r3.pem
    - assets/ca/globalsign-gcc-r6-alphassl-ca-2023.pem

  fonts:
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf

